---
title: "Bayesian"
author: "Wesley Kammeraad"
date: "21-1-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
installed_packages <- installed.packages()[, "Package"]

## Install Missing Required Packages
if (!"tidyverse" %in% installed_packages) {
  install.packages("tidyverse")
  }
if (!"qgraph" %in% installed_packages) {
  install.packages("qgraph")
}
if (!"dplyr" %in% installed_packages) {
  install.packages("dplyr")
}
if (!"psych" %in% installed_packages) {
  install.packages("magrittr")
}
if (!"bootnet" %in% installed_packages) {
  install.packages("bootnet")
}
if (!"mgm" %in% installed_packages) {
  install.packages("mgm")
}
if (!"janitor" %in% installed_packages) {
  install.packages("janitor")
}
if (!requireNamespace("BiocManager", quietly = TRUE)){
  install.packages("BiocManager")
  BiocManager::install("Rgraphviz")
}
    

## Load packages
library("tidyverse")
library("qgraph")
library("dplyr")
library("magrittr")
library("bootnet")
library("mgm")
library("janitor")
library("bnlearn")
library("Rgraphviz")
```

```{r load_raw_data}
cohorts <- c("1718", "1819", "1920")

# Load and combine the three CSVs
raw_data <- data.frame()
for (cohort in cohorts) {
  file <- paste0("data/anonymized_cohort", cohort, ".csv")
  
  cohort_data <- read_csv2(file) %>%
    clean_names() %>% 
    mutate(
      # Add a new column "cohort"
      cohort = cohort
    )

  
  # Add new cohorts data to joined data frame
  raw_data <- bind_rows(
    raw_data,
    cohort_data
  )
}
```

```{r tidy_data}
# Create a tidy dataframe with a subset of the data
full_tidy_data <- raw_data %>% 
  transmute(
    # Parse the grade as a decimal number
    grade = parse_number(
      offic_cijfer,
      locale = locale(decimal_mark = ",", grouping_mark = ".")
    ) %>%
      suppressWarnings,
    # Put all special grades (i.e. letters) into a separate column
    grade_special = if_else(is.na(grade), offic_cijfer, as.character(NA)),
    # Rename & select other columns
    specialisation = specialisatie,
    course_id = studiegids,
    student_id = masked_id,
    # The short description has different column names in different cohorts
    short_description = if_else(is.na(omschr_10), omschr_11, omschr_10),
    long_description = curs_omschr_l,
    cohort = cohort,
    rank = rangnummer,
    country = land
  )
```

```{r filter_data}
selected_courses <- c(
  "7201602PXY", # 1. Introduction Psychology & Cognition
  "7201604PXY", # 2. Research Methods & Statistics
  "7201605PXY", # 3. Developmental Psy
  "7201607PXY", # 4. Social & Work Psy
  "7201610PXY" # 5. Clinical & Biological Psy
)

data <- full_tidy_data %>%
  # Only include students who picked a specialisation
  filter(!is.na(specialisation) & specialisation != "0") %>% 
  filter(specialisation != "Algemene Psychologie") %>% 
  # Include only first year courses
  filter(course_id %in% selected_courses)
```

```{r}
data %<>%
  select(specialisation, student_id, grade, course_id) %>%
  pivot_wider(.,
              names_from = course_id,
              values_from = grade) %>%
    ungroup() %>%
      select(-student_id)
```

```{r}
# Assigning uniform column names for the courses
colnames(data) <-
  c("Specialization",
    "IP&C",
    "RM&S",
    "DevPsy",
    "S&WO",
    "C&B")

data
```

---------------------------------------------------------------------------------------------------------------

### Bayesian Network

```{r}
set.seed(55)
dataBN <- na.omit(data[,-1])
estBN <- hc(dataBN,
            restart = 10,
            perturb = 100)

estBN
```

```{r}
(edgeStrength <- arc.strength(estBN, dataBN, "bic-g"))
```

```{r}
strength.plot(estBN,
              edgeStrength,
              main = "Bayesian Network",
              shape = "ellipse")
```
```{r}
set.seed(333)
bootBN <- boot.strength(dataBN,
                        R = 500,
                        algorithm = "hc")
```

```{r}
averageBN <- averaged.network(bootBN,
                              threshold = .95) # Edges appear in 95% of estimated networks

edgeStrengthAvg <- arc.strength(averageBN,
                                dataBN,
                                "bic-g")

strength.plot(averageBN,
              edgeStrengthAvg,
              main = "Bootstrapped Bayesian",
              shape = "ellipse")
```
```{r}
subEdge <- bootBN[bootBN$strength > 0.95,]
subEdge
```

```{r}
bootTab <- bootBN[bootBN$strength > 0.85 &
                    bootBN$direction > 0.5,]
avgStr <- bootTab
avgStr$strength <- bootTab$direction

strength.plot(averageBN,
              avgStr,
              main = "Averaged Bayesian Network",
              shape = "ellipse")
```

