---
title: "Exploratory Analyses"
author: "Jan Simson, Wessley Kameraad, René Freichel"
date: "18.01.2021"
output: html_document
---

```{r load_raw_data}
library(tidyverse)
library(janitor)

cohorts <- c("1718", "1819", "1920")

# Load and combine the three CSVs
raw_data <- data.frame()
for (cohort in cohorts) {
  file <- paste0("data/anonymized_cohort", cohort, ".csv")
  
  cohort_data <- read_csv2(file) %>%
    clean_names() %>% 
    mutate(
      # Add a new column "cohort"
      cohort = cohort
    )

  
  # Add new cohorts data to joined data frame
  raw_data <- bind_rows(
    raw_data,
    cohort_data
  )
}
```

```{r tidy_data}
# Create a tidy dataframe with a subset of the data
tidy_data <- raw_data %>% 
  transmute(
    # Parse the grade as a decimal number
    grade = parse_number(
      offic_cijfer,
      locale = locale(decimal_mark = ",", grouping_mark = ".")
    ) %>%
      suppressWarnings,
    # Put all special grades (i.e. letters) into a separate column
    grade_special = if_else(is.na(grade), offic_cijfer, as.character(NA)),
    # Rename & select other columns
    specialisation = specialisatie,
    course_id = studiegids,
    student_id = masked_id,
    # The short description has different column names in different cohorts
    short_description = if_else(is.na(omschr_10), omschr_11, omschr_10),
    long_description = curs_omschr_l,
    cohort = cohort,
    rank = rangnummer,
    country = land
  )

# Compute relative grades
tidy_data <- tidy_data %>%
  # Calculate grades relative to *average course grade*
  group_by(cohort, course_id) %>% 
  mutate(
    # Z-Scored
    z_grade_course = scale(grade),
    # Only centered on mean
    m_grade_course = grade - mean(grade, na.rm = T)
  ) %>% 
  ungroup() %>% 
  # Calculate grades relative to *student's average grade*
  group_by(cohort, student_id) %>% 
  mutate(
    # Z-Scored
    z_grade_student = scale(grade),
    # Only centered on mean
    m_grade_student = grade - mean(grade, na.rm = T),
    # Centered on mean for course and then also per student
    m_grade_student_course = m_grade_course - mean(m_grade_course, na.rm = T)
  ) %>% 
  ungroup()

# Subset of data with useful specialisation info
spec_data <- tidy_data %>% 
  filter(!is.na(specialisation) & specialisation != "0")

# TODO: maybe match courses across years e.g. 7201622PXY is similar to 7201610PXY
```

```{r data_checks}
tidy_data %>% distinct(course_id) %>% nrow()
tidy_data %>% distinct(short_description) %>% nrow()
tidy_data %>% distinct(long_description) %>% nrow()

tidy_data %>% distinct(course_id, .keep_all = T) %>% filter(is.na(short_description)) %>% nrow()

tidy_data %>% distinct(course_id, short_description, long_description)
```


```{r counts}
# A few quick counts to see how much data is available
tidy_data %>%
  distinct(student_id, specialisation) %>% 
  count(specialisation)

tidy_data %>%
  distinct(student_id, specialisation, cohort) %>% 
  count(specialisation, cohort) %>% 
  group_by(cohort) %>%
  mutate(
    frac_cohort = round(n / sum(n), digits = 2)
  )

# Some more descriptibe counts
spec_data %>% distinct(student_id) %>% nrow()
spec_data %>% distinct(student_id, .keep_all = T) %>% group_by(specialisation) %>% count()
spec_data %>% distinct(student_id, .keep_all = T) %>% group_by(specialisation, cohort) %>% count()

tidy_data %>% 
  filter(cohort == "1920" | specialisation != "0") %>%
  distinct(student_id, .keep_all = T) %>% 
  ggplot(aes(x = cohort, fill = specialisation)) +
  geom_bar(position = "fill") +
  # scale_fill_brewer(type = "qual", palette = "Set1", direction = -1, na.value = "grey") +
  theme_minimal() +
  labs(
    x = "Cohort",
    y = "Fraction of Students",
    fill = "Specialisation"
  )
```


```{r top_N_courses}
# Get a list of courses with many students
top_courses_info <- spec_data %>%
  # Only count courses w/ grades
  filter(!is.na(grade)) %>% 
  count(course_id, short_description, cohort) %>% 
  group_by(course_id) %>% 
  # Minimum N across cohorts
  mutate(min_n = min(n)) %>% 
  # Only courses with at least 100 grades in each cohort
  filter(min_n > 150)
top_courses <- top_courses_info %>%
  pull(course_id)

# Use top-courses by N
# selected_courses <- top_courses

# Manually select first-year courses
selected_courses <- c(
  "7201602PXY", # 1. Introduction Psychology & Cognition
  "7201604PXY", # 2. Research Methods & Statistics
  "7201605PXY", # 3. Developmental Psy
  "7201607PXY", # 4. Social & Work Psy
  "7201610PXY" # 5. Clinical & Biological Psy
)
```


```{r reshapingFunction}
# Helper function to quickly generate wide grade data using different
# types of grades
generate_wide_grades <- function (grade_column) {
  spec_data %>%
    filter(course_id %in% selected_courses) %>% 
    pivot_wider(
      id_cols = student_id,
      names_from = short_description,
      
      # Use variable to assign grade column
      values_from = grade_column
    )
}
```

```{r networks, message=FALSE, warning=FALSE}
# Fit some first, very preliminary networks
# these are currently fitted over all specialisations, because the N is so small
# at only N = ~500
library(bootnet)

grade_columns <- c(
  "grade", 
  "m_grade_course", 
  "z_grade_course", 
  "m_grade_student", 
  "z_grade_student", 
  "m_grade_student_course"
)
for (grade_column in grade_columns) {
  temp_wide_grades <- generate_wide_grades(grade_column = grade_column) %>% 
    select(-student_id)
  
  # Abbreviate column names for network plots
  abb <- colnames(temp_wide_grades) %>% abbreviate()
  colnames(temp_wide_grades) <- abb
  print(abb)
  
  nw_pcor <- estimateNetwork(
    temp_wide_grades,
    default = "pcor",
    missing = "pairwise"
  )
  plot(nw_pcor, title = paste0("NW: pcor, Data: ", grade_column), layout = "circle")
  
  nw_EBICglasso <- estimateNetwork(
    temp_wide_grades,
    default = "EBICglasso",
    missing = "pairwise"
  )
  plot(nw_EBICglasso, title = paste0("NW: EBICglasso, Data: ", grade_column), layout = "circle")
  
  nw_ggmModSelect <- estimateNetwork(
    temp_wide_grades,
    default = "ggmModSelect",
    missing = "pairwise"
  )
  plot(nw_ggmModSelect, title = paste0("NW: ggmModSelect, Data: ", grade_column), layout = "circle")
}

```

```{r reshape}
# Transform data into wide format with one row per student and
# one column per (top) course. Only using the top courses here
# to avoid a ton of NAs in the matrix
grades_wide <- generate_wide_grades("m_grade_student_course")

# Matrix of specialisations in wide format
specialisations_wide <- spec_data %>% 
  distinct(student_id, .keep_all = T) %>% 
  mutate(one = 1) %>% 
  pivot_wider(id_cols = student_id, names_from = specialisation, values_from = one) %>% 
  mutate(across(everything(), ~replace_na(.x, 0)))
```

```{r compare_networks}
# Split grades_wide data into 2 separate dataframes,
# based on whether they chose clinical psych or not as specialisation
grades_wide_spec_long <- grades_wide %>%
  left_join(tidy_data %>% select(student_id, specialisation), by = "student_id")

grades_wide_clinical <- grades_wide_spec_long %>% 
  filter(specialisation == "Spec Klinische Psychologie")
grades_wide_non_clinical <- grades_wide_spec_long %>% 
  filter(specialisation != "Spec Klinische Psychologie")

rm(grades_wide_spec_long)

fit_network <- . %>% 
  # Remove unnecessary columns
  select(-student_id, -specialisation) %>% 
  # Shorten names
  rename_at(vars(everything()), abbreviate) %>% 
  # Fit the network
  estimateNetwork(
    default = "ggmModSelect",
    missing = "pairwise"
  )

nw_clinical <- fit_network(grades_wide_clinical)
nw_non_clinical <- fit_network(grades_wide_non_clinical)

plot(nw_clinical, title = "Clinical NW", layout = "circle")
plot(nw_non_clinical, title = "Non-Clinical NW", layout = "circle")
```


```{r correlation_plot}
# Explore possible relationships in a correlation plot
joined_matrix <- left_join(grades_wide, specialisations_wide)

corrs <- cor(joined_matrix %>% select(-student_id), use = "pairwise")
corrplot::corrplot(corrs)
```
