---
title: "Final Report - R-Code - Exploring the possibility to predict student specialization choice from student profiles"
author: "Wessley Kameraad, René Freichel, Jan Simson"
date: "04.01.2021 - 29.01.2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
installed_packages <- installed.packages()[, "Package"]

## Install Missing Required Packages
if (!"tidyverse" %in% installed_packages) {
  install.packages("tidyverse")
  }
if (!"qgraph" %in% installed_packages) {
  install.packages("qgraph")
}
if (!"dplyr" %in% installed_packages) {
  install.packages("dplyr")
}
if (!"magrittr" %in% installed_packages) {
  install.packages("magrittr")
}
if (!"bootnet" %in% installed_packages) {
  install.packages("bootnet")
}
if (!"mgm" %in% installed_packages) {
  install.packages("mgm")
}
if (!"janitor" %in% installed_packages) {
  install.packages("janitor")
}
if (!requireNamespace("BiocManager", quietly = TRUE)){
  install.packages("BiocManager")
  BiocManager::install("Rgraphviz")
}
    

## Load packages
library("tidyverse")
library("qgraph")
library("dplyr")
library("magrittr")
library("bootnet")
library("mgm")
library("janitor")
library("bnlearn")
library("Rgraphviz")
library("nnet")

set.seed(2021)
```

```{r load_raw_data, message=FALSE, warning=FALSE}
cohorts <- c("1718", "1819", "1920")

# Load and combine the three CSVs
raw_data <- data.frame()
for (cohort in cohorts) {
  file <- paste0("data/anonymized_cohort", cohort, ".csv")
  
  cohort_data <- read_csv2(file) %>%
    clean_names() %>% 
    mutate(
      # Add a new column "cohort"
      cohort = cohort
    )

  
  # Add new cohorts data to joined data frame
  raw_data <- bind_rows(
    raw_data,
    cohort_data
  )
}
```

```{r tidy_data}
# Create a tidy dataframe with a subset of the data
full_tidy_data <- raw_data %>% 
  transmute(
    # Parse the grade as a decimal number
    grade = parse_number(
      offic_cijfer,
      locale = locale(decimal_mark = ",", grouping_mark = ".")
    ) %>%
      suppressWarnings,
    # Put all special grades (i.e. letters) into a separate column
    grade_special = if_else(is.na(grade), offic_cijfer, as.character(NA)),
    # Rename & select other columns
    specialisation = specialisatie,
    course_id = studiegids,
    student_id = masked_id,
    # The short description has different column names in different cohorts
    short_description = if_else(is.na(omschr_10), omschr_11, omschr_10),
    long_description = curs_omschr_l,
    cohort = cohort,
    rank = rangnummer,
    country = land
  )
```

```{r filter_data}
selected_courses <- c(
  "7201602PXY", # 1. Introduction Psychology & Cognition
  "7201604PXY", # 2. Research Methods & Statistics
  "7201605PXY", # 3. Developmental Psy
  "7201607PXY", # 4. Social & Work Psy
  "7201622PXY" # 5. Clinical Psychology & Brain
  # 5. is matched with "7201610PXY": Clinical & Biological Psy (1718)
)

# Merge the two courses across cohorts:
# Clinical Psychology & Brain (cohorts 1819, 1920)
# Clinical & Biological Psy (cohort 1718)
# and remove any instances where a student has taken both courses
# (that means they failed the first one, so that is dropped)
students_with_double_bio_courses <- full_tidy_data %>%
  filter(course_id %in% c("7201622PXY", "7201610PXY")) %>% 
  count(student_id) %>% 
  filter(n > 1) %>% 
  pull(student_id)
full_tidy_data <- full_tidy_data %>%
  filter(
    # Only keep the newer bio course if a student has both
    # (this means they failed to complete the old bio course)
    course_id != "7201610PXY" | !(student_id %in% students_with_double_bio_courses)
  ) %>% 
  mutate(
    course_id = if_else(course_id == "7201610PXY", "7201622PXY", course_id),
    short_description = if_else(
      course_id == "7201622PXY",
      "Clinical Psychology & Brain / Bio",
      short_description
    ),
    long_description = if_else(
      course_id == "7201622PXY", 
      "[Combined] Clinical Psychology & Brain + Clinical & Biological Psy", 
      long_description
    )
  )

data <- full_tidy_data %>%
  # Only include students who picked a specialisation
  filter(!is.na(specialisation) & specialisation != "0") %>% 
  filter(specialisation != "Algemene Psychologie") %>% 
  # Include only first year courses
  filter(course_id %in% selected_courses)
```

```{r}
course_abbrevations <- c(
  "7201602PXY" = "IPC",
  "7201604PXY" = "RMS",
  "7201605PXY" = "DEV",
  "7201607PXY" = "SWO",
  "7201622PXY" = "CB"
)

data_wide <- data %>%
  select(specialisation, grade, course_id, student_id) %>%
  mutate(course_id = recode(course_id, !!!course_abbrevations)) %>% 
  group_by(student_id) %>%
  pivot_wider(
    .,
    names_from = course_id,
    values_from = grade
  ) %>%
  ungroup() %>% 
  rename(Specialization = specialisation, ID = student_id)
data_wide
```

***

## Descriptives

```{r counting}
# Table of students per picked specialisation
full_tidy_data %>%
  filter(!is.na(specialisation)) %>% 
  distinct(student_id, .keep_all = T) %>% 
  mutate(
    specialisation = if_else(
      specialisation %in% c("0", "Algemene Psychologie"),
      "Did not (yet) pick a specialisation",
      specialisation
    )
  ) %>% 
  group_by(specialisation, cohort) %>% 
  count() %>% 
  pivot_wider(specialisation, names_from = cohort, values_from = n) %>% 
  mutate(
    Total = `1718` + `1819`
  ) %>%
  rename(
    Specialisation = specialisation,
    `17-18` = `1718`,
    `18-19` = `1819`
  ) %>% 
  knitr::kable()

full_tidy_data %>% 
  filter(cohort == "1920" | !specialisation %in% c("0", "Algemene Psychologie")) %>%
  distinct(student_id, .keep_all = T) %>% 
  ggplot(aes(x = cohort, fill = specialisation)) +
  geom_bar(position = "fill") +
  theme_minimal() +
  labs(
    x = "Cohort",
    y = "Fraction of Students",
    fill = "Specialisation"
  )
```

```{r grade_distribution}
ggplot(data, aes(x = grade)) +
  geom_bar(fill = "#f6a70a") +
  facet_wrap(vars(short_description)) +
  labs(
    x = "Grade",
    y = "No. of Students"
  )
```

***
