---
title: "Report"
author: "Wessley Kameraad, René Freichel, Jan Simson"
date: "18.01.2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_raw_data}
library(tidyverse)
library(janitor)

cohorts <- c("1718", "1819", "1920")

# Load and combine the three CSVs
raw_data <- data.frame()
for (cohort in cohorts) {
  file <- paste0("data/anonymized_cohort", cohort, ".csv")
  
  cohort_data <- read_csv2(file) %>%
    clean_names() %>% 
    mutate(
      # Add a new column "cohort"
      cohort = cohort
    )

  
  # Add new cohorts data to joined data frame
  raw_data <- bind_rows(
    raw_data,
    cohort_data
  )
}
```

```{r tidy_data}
# Create a tidy dataframe with a subset of the data
full_tidy_data <- raw_data %>% 
  transmute(
    # Parse the grade as a decimal number
    grade = parse_number(
      offic_cijfer,
      locale = locale(decimal_mark = ",", grouping_mark = ".")
    ) %>%
      suppressWarnings,
    # Put all special grades (i.e. letters) into a separate column
    grade_special = if_else(is.na(grade), offic_cijfer, as.character(NA)),
    # Rename & select other columns
    specialisation = specialisatie,
    course_id = studiegids,
    student_id = masked_id,
    # The short description has different column names in different cohorts
    short_description = if_else(is.na(omschr_10), omschr_11, omschr_10),
    long_description = curs_omschr_l,
    cohort = cohort,
    rank = rangnummer,
    country = land
  )
```

```{r filter_data}
selected_courses <- c(
  "7201602PXY", # 1. Introduction Psychology & Cognition
  "7201604PXY", # 2. Research Methods & Statistics
  "7201605PXY", # 3. Developmental Psy
  "7201607PXY", # 4. Social & Work Psy
  "7201622PXY" # 5. Clinical Psychology & Brain
  # 5. is matched with "7201610PXY": Clinical & Biological Psy (1718)
)

# Merge the two courses across cohorts:
# Clinical Psychology & Brain (cohorts 1819, 1920)
# Clinical & Biological Psy (cohort 1718)
# and remove any instances where a student has taken both courses
# (that means they failed the first one, so that is dropped)
students_with_double_bio_courses <- full_tidy_data %>%
  filter(course_id %in% c("7201622PXY", "7201610PXY")) %>% 
  count(student_id) %>% 
  filter(n > 1) %>% 
  pull(student_id)
full_tidy_data <- full_tidy_data %>%
  filter(
    # Only keep the newer bio course if a student has both
    # (this means they failed to complete the old bio course)
    course_id != "7201610PXY" | !(student_id %in% students_with_double_bio_courses)
  ) %>% 
  mutate(
    course_id = if_else(course_id == "7201610PXY", "7201622PXY", course_id),
    short_description = if_else(
      course_id == "7201622PXY",
      "Clinical Psychology & Brain / Bio",
      short_description
    ),
    long_description = if_else(
      course_id == "7201622PXY", 
      "[Combined] Clinical Psychology & Brain + Clinical & Biological Psy", 
      long_description
    )
  )

data <- full_tidy_data %>%
  # Only include students who picked a specialisation
  filter(!is.na(specialisation) & specialisation != "0") %>% 
  filter(specialisation != "Algemene Psychologie") %>% 
  # Include only first year courses
  filter(course_id %in% selected_courses)
```

